Book library2
blase147/awesome-books pull request #2
Opened 2022-09-27 11:55 UTC by blase147

2022-09-27 13:09 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @blase147 and @Diana-Duya,

Good job so far!
✔️ Books can be added on the page
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the **[OPTIONAL]** prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-27 13:09 UTC, TedLivist commented on README.md
> +# PORTFOLIO PROJECT
- [ ] Kindly take another look at your entire README. This is an awesome books project whereas some of your README sections contain details about the portfolio project. Kindly fix that.

2022-09-27 13:09 UTC, TedLivist commented on js/script.js
> +});
- [ ] There is an issue with your application. For the first book when I move the title and author inputs, the local storage gets initialized. Now for the subsequent entries, the same book title and author that was added initially is what is updated. No new book is being added. Kindly note that each book should be added to the local storage and the page.

  You can see that the only existing book is the second one that was added

  ![eew](https://user-images.githubusercontent.com/36542986/192533712-f0dd52f7-4d90-4eba-8c10-9c5f1c9006bd.jpg)

- [ ] I don't think it is necessary to modify the localStorage when a user changes from the inputs. We can simply add data to the localStorage only when the user click on the "Add" button

2022-09-27 13:09 UTC, TedLivist commented on js/script.js
> +  }
- [ ] Your book removal does not work as expected. All changes should be saved in the local storage. When I removed all the books from the page, the one in the localStorage was still there. Kindly fix that.

2022-09-27 13:09 UTC, TedLivist commented on js/script.js
> +
- [ ] **[OPTIONAL]**  I think it would be a good idea to clear the inputs after a user has added a book for a better user experience.

2022-09-27 13:09 UTC, TedLivist commented on js/script.js
> +//  Adding books to library
- [ ] When I reload the page, the books from the localStorage are not displayed on the page. Kindly ensure that on page reload all books on the `localStorage` are loaded and displayed on the page.

2022-09-28 11:18 UTC, julie-ify approved these changes
Hi @blase147 and @Diana-Duya,

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-28 11:19 UTC, merged